import sqlite3

gerador_astronergy = {
    "Fabricante": "Astronergy",
    "SIGLA": "CHSM6612M/HV - 375W",
    "Tec_construcao": "Monocristalino",
    "Garantia": "10 anos",
    "Pot_max": "375 W",
    "Eficiencia": "19,4 %",
    "Tensao_nom": "39,76 V",
    "Tensao_aberto": "48,45 V",
    "Corrente_nom": "9,45 A",
    "Corrente_cc": "9,94 A",
    "axlxp": "1960 x 992 x 40 mm",
    "Peso": "21,8 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}
gerador_astronergy_600 = {
    "Fabricante": "Astronergy",
    "SIGLA": "CHSM66RN(DG)/F-BH-600W",
    "Tec_construcao": "Monocristalino",
    "Garantia": "12 anos",
    "Pot_max": "600 W",
    "Eficiencia": "22,2 %",
    "Tensao_nom": "41,05 V",
    "Tensao_aberto": "48,44 V",
    "Corrente_nom": "14,64 A",
    "Corrente_cc": "15,78 A",
    "axlxp": "2382 x 1134 x 30 mm",
    "Peso": "33,5 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}
gerador_canadian = {
    "Fabricante": "Canadian Solar",
    "SIGLA": "TCS6U-330P",
    "Tec_construcao": "Policristalino",
    "Garantia": "12 anos",
    "Pot_max": "330 W",
    "Eficiencia": "16,97 %",
    "Tensao_nom": "37,2 V",
    "Tensao_aberto": "45,6 V",
    "Corrente_nom": "8,88 A",
    "Corrente_cc": "9,45 A",
    "axlxp": "1990 x 992 x 40 mm",
    "Peso": "22,4 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}
gerador_gokin = {
    "Fabricante": "Gokin Solar",
    "SIGLA": "GK-1-72HT585M",
    "Tec_construcao": "Monocristalino",
    "Garantia": "12 anos",
    "Pot_max": "585 W",
    "Eficiencia": "22,6%",
    "Tensao_nom": "42.74 V",
    "Tensao_aberto": "51.67 V",
    "Corrente_nom": "13.69 A",
    "Corrente_cc": "14.43 A",
    "axlxp": "2310x1125x1259mm",
    "Peso": "26,8 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}
gerador_gokin_700 = {
    "Fabricante": "Gokin Solar",
    "SIGLA": "GK-2-66HTBD-700M",
    "Tec_construcao": "Monocristalino",
    "Garantia": "12 anos",
    "Pot_max": "700 W",
    "Eficiencia": "22,5 %",
    "Tensao_nom": "41,1 V",
    "Tensao_aberto": "47,9 V",
    "Corrente_nom": "17,04 A",
    "Corrente_cc": "18,8 A",
    "axlxp": "2384 x 1303 x 33 mm",
    "Peso": "37,5 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}
gerador_hanersun_585 = {
    "Fabricante": "Hanersun",
    "SIGLA": "HN18-72H585",
    "Tec_construcao": "Monocristalino",
    "Garantia": "12 anos",
    "Pot_max": "585 W",
    "Eficiencia": "22,65%",
    "Tensao_nom": "40,80 V",
    "Tensao_aberto": "49,30 V",
    "Corrente_nom": "10,91 A",
    "Corrente_cc": "11,53 A",
    "axlxp": "2278 x 1134 x 30mm",
    "Peso": "28,5 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}
gerador_hanersun_610 = {
    "Fabricante": "Hanersun",
    "SIGLA": "HN21RN-66HT610W",
    "Tec_construcao": "Monocristalino",
    "Garantia": "12 anos",
    "Pot_max": "610 W",
    "Eficiencia": "22,6 %",
    "Tensao_nom": "40,59 V",
    "Tensao_aberto": "48,72 V",
    "Corrente_nom": "15,03 A",
    "Corrente_cc": "15,94 A",
    "axlxp": "2382 x 1134 x 30 mm",
    "Peso": "33,5 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}
gerador_honor_700 = {
    "Fabricante": "Honor Solar",
    "SIGLA": "HY-M12/132G-700",
    "Tec_construcao": "Monocristalino",
    "Garantia": "12 anos",
    "Pot_max": "700 W",
    "Eficiencia": "22,5 %",
    "Tensao_nom": "41,78 V",
    "Tensao_aberto": "49,83 V",
    "Corrente_nom": "16,77 A",
    "Corrente_cc": "17,82 A",
    "axlxp": "2384 x 1303 x 33 mm",
    "Peso": "37,5 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}
gerador_znshine_700 = {
    "Fabricante": "ZNSHINE SOLAR",
    "SIGLA": "ZXM8-GPLD132-700W",
    "Tec_construcao": "Monocristalino N-Type TOPCon Double Glass",
    "Garantia": "12 anos",
    "Pot_max": "700 W",
    "Eficiencia": "22,53 %",
    "Tensao_nom": "40,40 V",
    "Tensao_aberto": "48,20 V",
    "Corrente_nom": "17,33 A",
    "Corrente_cc": "18,32 A",
    "axlxp": "2384 x 1303 x 35 mm",
    "Peso": "38,5 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}
gerador_gokin_610 = {
    "Fabricante": "GOKIN SOLAR",
    "SIGLA": "GK-4-66HTBD-610M-F",
    "Tec_construcao": "Monocristalino N-Type TOPCon Dual Glass (Bifacial)",
    "Garantia": "15 anos",
    "Pot_max": "610 W",
    "Eficiencia": "22,6 %",
    "Tensao_nom": "40,22 V",
    "Tensao_aberto": "48,00 V",
    "Corrente_nom": "15,18 A",
    "Corrente_cc": "16,07 A",
    "axlxp": "2382 x 1134 x 30 mm",
    "Peso": "33,0 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}
gerador_trina_400 = {
    "Fabricante": "Trina Solar",
    "SIGLA": "TSM-400DE09",
    "Tec_construcao": "Monocristalino",
    "Garantia": "12 anos",
    "Pot_max": "400 W",
    "Eficiencia": "20,8 %",
    "Tensao_nom": "34,2 V",
    "Tensao_aberto": "41,2 V",
    "Corrente_nom": "11,70 A",
    "Corrente_cc": "12,28 A",
    "axlxp": "1754 x 1096 x 30 mm",
    "Peso": "21,0 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}
gerador_risen_700 = {
    "Fabricante": "Risen Energy",
    "SIGLA": "RSM132-8-700BHDG",
    "Tec_construcao": "Heterojunção (HJT)",
    "Garantia": "15 anos",
    "Pot_max": "700 W",
    "Eficiencia": "22,5 %",
    "Tensao_nom": "41,78 V",
    "Tensao_aberto": "49,83 V",
    "Corrente_nom": "16,77 A",
    "Corrente_cc": "17,82 A",
    "axlxp": "2384 x 1303 x 33 mm",
    "Peso": "37,5 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}
gerador_honor_600 = {
    "Fabricante": "Honor Solar",
    "SIGLA": "HY-M16/144H-600",
    "Tec_construcao": "Monocristalino N-Type TOPCon",
    "Garantia": "15 anos",
    "Pot_max": "600 W",
    "Eficiencia": "22,2 %",
    "Tensao_nom": "43,90 V",
    "Tensao_aberto": "52,34 V",
    "Corrente_nom": "13,67 A",
    "Corrente_cc": "14,53 A",
    "axlxp": "2384 x 1134 x 30 mm",
    "Peso": "28,2 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}
gerador_hanersun_700 = {
    "Fabricante": "HANERSUN",
    "SIGLA": "HN21N-66HT700W",
    "Tec_construcao": "Monocristalino N-Type TOPCon Bifacial",
    "Garantia": "15 anos",
    "Pot_max": "700 W",
    "Eficiencia": "22,5 %",
    "Tensao_nom": "40,40 V",
    "Tensao_aberto": "48,20 V",
    "Corrente_nom": "17,33 A",
    "Corrente_cc": "18,34 A",
    "axlxp": "2384 x 1303 x 33 mm",
    "Peso": "37,4 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}
gerador_osda_610 = {
    "Fabricante": "OSDA SOLAR",
    "SIGLA": "ODA610-33V-MHDRz",
    "Tec_construcao": "N-Type Bifacial Monocristalino",
    "Garantia": "15 anos",
    "Pot_max": "610 W",
    "Eficiencia": "22,58 %",
    "Tensao_nom": "41,38 V",
    "Tensao_aberto": "48,68 V",
    "Corrente_nom": "14,74 A",
    "Corrente_cc": "15,66 A",
    "axlxp": "2382 x 1134 x 30 mm",
    "Peso": "32,40 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}

gerador_trina_695 = {
    "Fabricante": "Trina Solar",
    "SIGLA": "TSM-NEG21C.20",
    "Tec_construcao": "N-type Bifacial Dual Glass Monocristalino",
    "Garantia": "12 anos",
    "Pot_max": "695 W",
    "Eficiencia": "22,4 %",
    "Tensao_nom": "40,3 V",
    "Tensao_aberto": "48,3 V",
    "Corrente_nom": "17,25 A",
    "Corrente_cc": "18,28 A",
    "axlxp": "2384 x 1303 x 33 mm",
    "Peso": "38,3 kg",
    "Imagem_gerador": "Imagens/Trina_gerador.jpg",
}

modulos = [
    gerador_astronergy,
    gerador_astronergy_600,
    gerador_canadian,
    gerador_gokin,
    gerador_gokin_700,
    gerador_hanersun_585,
    gerador_hanersun_610,
    gerador_honor_700,
    gerador_znshine_700,
    gerador_gokin_610,
    gerador_trina_400,
    gerador_risen_700,
    gerador_honor_600,
    gerador_hanersun_700,
    gerador_osda_610,
    gerador_trina_695,
]

inversor_growatt2 = {
    "Fabricante_sigla": "Growatt NEO 2000M-X",
    "Entradas": "4",
    "Monitoramento": "SIM – Wireless",
    "Pot_nom_max": "2 kW",
    "Tensao_nom_freq": "220 V - 54/65 Hz",
    "Tensao_max": "65 VCC",
    "Tensao_saida": "160 – 285 V",
    "Corrente_max_saida": "9,3 A",
    "Eficiencia_max": "96,5 %",
    "axlxp_inv": "396 × 300 × 45 mm",
    "Peso_inv": "5 kg",
    "Nome_inversor": "Growatt",
    "Link_inversor": "https://server.growatt.com/login",
    "App_inversor": "ShinePhone",
    "Imagem_inversor": "Imagens/inversor_growatt_2kw.jpg",
}
inversor_growatt225 = {
    "Fabricante_sigla": "Growatt NEO 2250M-X2",
    "Entradas": "4",
    "Monitoramento": "SIM – Wireless",
    "Pot_nom_max": "2.25 kW",
    "Tensao_nom_freq": "35 V - 50/60 Hz",
    "Tensao_max": "60 VCC",
    "Tensao_saida": "220 V",
    "Corrente_max_saida": "10,23 A",
    "Eficiencia_max": "96,5%",
    "axlxp_inv": "396*270*45 mm",
    "Peso_inv": "5,1 kg",
    "Nome_inversor": "Growatt",
    "Link_inversor": "https://server.growatt.com/login",
    "App_inversor": "ShinePhone",
    "Imagem_inversor": "Imagens/inversor_growatt.jpg",
}
inversor_Sungrow = {
    "Fabricante_sigla": "Sungrow SG3K-S",
    "Entradas": "1",
    "Monitoramento": "SIM – Wireless",
    "Pot_nom_max": "3 kW",
    "Tensao_nom_freq": "220 V - 60 Hz",
    "Tensao_max": "600 VCC",
    "Tensao_saida": "176 - 276 V",
    "Corrente_max_saida": "13,7 A",
    "Eficiencia_max": "98,2 %",
    "axlxp_inv": "370 x 300 x 125 mm",
    "Peso_inv": "8,5 kg",
    "Nome_inversor": "Sungrow",
    "Imagem_inversor": "Imagens/inversor_hoymiles.jpg",
    "Link_inversor": "",
    "App_inversor": "",
}
inversor_Hoymiles = {
    "Fabricante_sigla": "Hoymiles MI-1500 / MI-700",
    "Entradas": "2",
    "Monitoramento": "SIM – Wireless",
    "Pot_nom_max": "1,2 kW / 0,7 kW",
    "Tensao_nom_freq": "220 V - 45/65 Hz",
    "Tensao_max": "60 Vcc",
    "Tensao_saida": "180 - 275 V",
    "Corrente_max_saida": "5,21 A / 3,36 A",
    "Eficiencia_max": "96,50 % / 96,70%",
    "axlxp_inv": "176 x 280 x 33 mm",
    "Peso_inv": "3,75 kg",
    "Nome_inversor": "Hoymiles",
    "Imagem_inversor": "Imagens/inversor_hoymiles.jpg",
    "Link_inversor": "http://global.hoymiles.com",
    "App_inversor": "S-miles Enduser",
}
inversor_hoymiles_2000 = {
    "Fabricante_sigla": "Hoymiles HMS-2000-4T",
    "Entradas": "4",
    "Monitoramento": "SIM – Wireless",
    "Pot_nom_max": "2 kW",
    "Tensao_nom_freq": "220 V - 54/65 Hz",
    "Tensao_max": "65 VCC",
    "Tensao_saida": "183 – 228 V",
    "Corrente_max_saida": "9,22 A",
    "Eficiencia_max": "99,8 %",
    "axlxp_inv": "331 x 218 x 40.6 mm",
    "Peso_inv": "5,56 kg",
    "Nome_inversor": "Hoymiles",
    "Link_inversor": "http://global.hoymiles.com",
    "App_inversor": "S-miles Enduser",
    "Imagem_inversor": "Imagens/inversor_hoymiles.jpg",
}
inversor_hyxipower_m2000 = {
    "Fabricante_sigla": "Hyxipower HYX-M2000-SW",
    "Entradas": "4",
    "Monitoramento": "SIM – Wireless",
    "Pot_nom_max": "2 kW",
    "Tensao_nom_freq": "220 V - 50/60 Hz",
    "Tensao_max": "65 VCC",
    "Tensao_saida": "183 – 276 V",
    "Corrente_max_saida": "9,09 A",
    "Eficiencia_max": "96,70%",
    "axlxp_inv": "310*236*35.5mm",
    "Peso_inv": "5 kg",
    "Nome_inversor": "Hyxipower",
    "Link_inversor": "http://Hyxicloud.com",
    "App_inversor": "Hyxipower",
    "Imagem_inversor": "Imagens/inversor_hyxipower.jpg",
}
inversor_solis6k = {
    "Fabricante_sigla": "Solis S5-GR3P6K",
    "Entradas": "2",
    "Monitoramento": "SIM – Wireless",
    "Pot_nom_max": "6 kW",
    "Tensao_nom_freq": "380 V - 50/60 Hz",
    "Tensao_max": "1100 VCC",
    "Tensao_saida": "380 V",
    "Corrente_max_saida": "9.5 A",
    "Eficiencia_max": "98,3%",
    "axlxp_inv": "310 x 563 x 219 mm",
    "Peso_inv": "17,8 kg",
    "Nome_inversor": "Solis",
    "Link_inversor": "",
    "App_inversor": "",
    "Imagem_inversor": "Imagens/inversor_solis_6kw.jpg",
}
inversor_saj_r6_20k = {
    "Fabricante_sigla": "SAJ R6-20K-T3-32-LV",
    "Entradas": "3 MPPTs / 6 Strings",
    "Monitoramento": "SIM – Wi-Fi/Ethernet/4G",
    "Pot_nom_max": "20 kW",
    "Tensao_nom_freq": "220 V - 50/60 Hz",
    "Tensao_max": "1100 VCC",
    "Tensao_saida": "101.6 – 139.7 V (F-N)",
    "Corrente_max_saida": "57,7 A",
    "Eficiencia_max": "98,80 %",
    "axlxp_inv": "473*659.4*240 mm",
    "Peso_inv": "35,5 kg",
    "Nome_inversor": "SAJ Electric",
    "Link_inversor": "https://www.saj-electric.com",
    "App_inversor": "eSAJ Home / eSAJ Service",
    "Imagem_inversor": "Imagens/inversor_saj_r6.jpg",
}
inversor_Hoymiles_1200 = {
    "Fabricante_sigla": "Hoymiles MI-1200",
    "Entradas": "4",
    "Monitoramento": "SIM – Wireless",
    "Pot_nom_max": "1,2 kW",
    "Tensao_nom_freq": "220 V - 45/65 Hz",
    "Tensao_max": "60 Vcc",
    "Tensao_saida": "180 - 275 V",
    "Corrente_max_saida": "5,45 A",
    "Eficiencia_max": "96,50 %",
    "axlxp_inv": "176 x 280 x 33 mm",
    "Peso_inv": "3,75 kg",
    "Nome_inversor": "Hoymiles",
    "Imagem_inversor": "Imagens/inversor_hoymiles_1200.jpg",
    "Link_inversor": "http://www.hoymiles.com",
    "App_inversor": "S-miles Enduser",
}

inversores = [
    inversor_growatt2,
    inversor_growatt225,
    inversor_Sungrow,
    inversor_Hoymiles,
    inversor_hoymiles_2000,
    inversor_hyxipower_m2000,
    inversor_solis6k,
    inversor_saj_r6_20k,
    inversor_Hoymiles_1200,
]

conn = sqlite3.connect("equipamentos.db")
cursor = conn.cursor()
cursor.execute("DELETE FROM Modulos")
cursor.execute("DELETE FROM Inversores")

for mod in modulos:
    cursor.execute(
        """INSERT INTO Modulos(
        Fabricante, SIGLA, Tec_construcao, Garantia, Pot_max, Eficiencia,Tensao_nom, Tensao_aberto, Corrente_nom, Corrente_cc, axlxp, Peso, Imagem_gerador)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)""",
        (
            mod["Fabricante"],
            mod["SIGLA"],
            mod["Tec_construcao"],
            mod["Garantia"],
            mod["Pot_max"],
            mod["Eficiencia"],
            mod["Tensao_nom"],
            mod["Tensao_aberto"],
            mod["Corrente_nom"],
            mod["Corrente_cc"],
            mod["axlxp"],
            mod["Peso"],
            mod["Imagem_gerador"],
        ),
    )

for inv in inversores:
    cursor.execute(
        """INSERT INTO Inversores(
        Fabricante_sigla, Entradas, Monitoramento, Pot_nom_max,Tensao_nom_freq,Tensao_max,Tensao_saida,Corrente_max_saida,Eficiencia_max,axlxp_inv,Peso_inv,Nome_inversor,Link_inversor,App_inversor,Imagem_inversor)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (
            inv["Fabricante_sigla"],
            inv["Entradas"],
            inv["Monitoramento"],
            inv["Pot_nom_max"],
            inv["Tensao_nom_freq"],
            inv["Tensao_max"],
            inv["Tensao_saida"],
            inv["Corrente_max_saida"],
            inv["Eficiencia_max"],
            inv["axlxp_inv"],
            inv["Peso_inv"],
            inv["Nome_inversor"],
            inv["Link_inversor"],
            inv["App_inversor"],
            inv["Imagem_inversor"],
        ),
    )

conn.commit()
conn.close()
